server:
  port: 8010

# 多网卡环境下的IP选择  多网卡的服务器，各个微服务注册到Eureka server 上的ip 要如何指定？
# springcloud 提供了以下四种方式

#spring:
#  cloud:
#    inetutils:
#      # 1 忽略指定名称的网卡  忽略docker0网卡 以及所有以veth开头的网卡
#      ignored-interfaces:
#        - docker0
#        - veth.*
#      # 2 使用正则表达式，指定使用的网络地址
#      preferred-networks:
#        - 198.168
#        - 10.0
#      # 3 只使用站点本站地址
#      use-only-site-local-interfaces: true


eureka:
  client:
    service-url:
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
    #启动健康检查，通过此配置可将该服务中的健康状态传递到Eureka Server
#    healthcheck:
#      enabled: true
  instance:
    prefer-ip-address: true
    # 4 手动指定ip地址
#    ip-address: 127.0.0.1