server:
  port: 8031
spring:
  application:
    name: turbine-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
turbine:
  aggregator:
      clusterConfig: default
  app-config: hystrix-feign-fallback2,ribbon-consumer
#  cluster-name-expression: "default"


