server:
  port: 8010

# 多网卡环境下的IP选择  多网卡的服务器，各个微服务注册到Eureka server 上的ip 要如何指定？
# springcloud 提供了以下四种方式

#spring:
#  cloud:
#    inetutils:
#      # 1 忽略指定名称的网卡  忽略docker0网卡 以及所有以veth开头的网卡
#      ignored-interfaces:
#        - docker0
#        - veth.*
#      # 2 使用正则表达式，指定使用的网络地址
#      preferred-networks:
#        - 198.168
#        - 10.0
#      # 3 只使用站点本站地址
#      use-only-site-local-interfaces: true


eureka:
  instance:
    hostname: ribbon-consumer-customer
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    registry-fetch-interval-seconds: 30
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
#设置ribbon 负载均衡的规则 可以通过java 类实现，也可以通过以下配置文件方式实现
#设置ribbon 复杂均衡规则 为随机
ribbon-consumer-customer:
  ribbon:
    NfLoadBalancerRuleClassName: com.netfilx.loadbalancer.RandomRule
    #启动健康检查，通过此配置可将该服务中的健康状态传递到Eureka Server
#    healthcheck:
#      enabled: true
#  instance:
#    prefer-ip-address: true
#    # 4 手动指定ip地址
##    ip-address: 127.0.0.1